### ISSUE TITLE
Issue with encrypting with a particular Public Key.

### ISSUE THREAD

**Issue by ramsingla** [travist/jsencrypt#20]
When I use the key mention in the below then output on the encrypt function is false.
Is there anything wrong with the public key?

```
var encryptor = new JSEncrypt()
encryptor.setPublicKey( key )
encryptor.encrypt('Hello World!')  // -> returns false
```

-----BEGIN RSA PUBLIC KEY-----
MIICCgKCAgEAsfvDzLf4oH9q3lPsIoahV7VO0hj2J7nEbB0OcRoxA0UpsMpBjIit
tskK4jIgZ/gVdf2zCOTiw9BWuOPr+CymCTl7785JSVmXi+FVLrN3nXYbo7sqkusb
DmrvRMTenx8M/f7zMiAS9iUF+jkFNg5MDkw4xiXFzgS7SYBVyRKIkVLte3JRjCPJ
vAgj3ddvet3FTylX09xrXemXEKXixLyrZrKMhrn/IQ/C0cbC6afrWI0XeBMTvxxp
ce88hxFM9d2LjCLa1MGs2eIDGVa+lOTZlu4OP8lZ7YCIYo2amNQg4511Lqqhgsqg
dYuvCnw9O41KyX7v2lzxVyLFDquhAuVG5zngWArvYCqnRNJMUZl/MYLYGo1ioh1L
lslfYZBxV5k4D8lfsK92GSzY4zQ/LfPRdRHQ3rVJ9YTp0q4mzgIe0OShCK71FcN2
8o/rrp4Pg2DcqTLDUeCDAfJchMJzbJ3ZbjB6zt0lYXqIt/iDMHbHlKKtKqoed1El
gG3Jz969vw1RDKFJJg2DKHlZobLxLbFmS/iQ686l+iTC0D/RraKrp2v4H3YRpap/
uYnfkpIqONDC1ULxCzFot2iHsDUFhL2wDaCgBYME1tzr8Klk4aQs+zFiILUduzJO
SB1tgxprKg8fwO5zv3tRJs8QDf74Z1QkgTVCG5P60YHsj5DCPEWsyO8CAwEAAQ==
-----END RSA PUBLIC KEY-----

JS Console

```
encryptor: l
   default_key_size: 1024
   default_public_exponent: "010001"
   key: H
     coeff: null
     d: null
     dmp1: null
     dmq1: null
     e: 0    <------------- This seems to be culprit
     n: null
     p: null
     q: null
```

**Comment by SpoonOfDoom** [comment]
Was this ever resolved? I'm having the same issue, where parseKey is not able to read neither my public nor my private key (which we already successfully use in PHP and C#, so the keys are definitely valid).

**Comment by hokeycokey** [comment]
I'm also seeing this issue.  Did it get resolved?  Thankss.

**Comment by gramo44** [comment]
I got the same response "false" on mensaje_enviar
```
        var obj_cifrado = new JSEncrypt();
        obj_cifrado.setPublicKey(llavePublica1);
        var mensaje_enviar = obj_cifrado.encrypt(mensaje);
```
I generate keys using php in the following way:
```
        $config = array(
            "digest_alg" => "sha512",
            "private_key_bits" => 1024,
            "private_key_type" => OPENSSL_KEYTYPE_RSA,
        );

        $res = openssl_pkey_new($config);
        openssl_pkey_export($res, $privKey);
        file_put_contents($archivosllaves.".rsa", $privKey);

        $pubKey = openssl_pkey_get_details($res);
        $pubKey = $pubKey["key"];
        file_put_contents($archivosllaves.".rsa.pub", $pubKey);
```

**Comment by citizentim** [comment]
Respectfully, there is nothing wrong with the public key.  This library seems not to support something about it.  Mine are generated using OpenSSL and I'm seeing the same behaviour as others - returns false after running encrypt()

I respectfully suggest that this case be reopened to investigate why the issue is occurring and resolve it.  

Also, FYI, the link provided as a justification for closure no longer works.

My public key is:

-----BEGIN CERTIFICATE-----
MIIDvDCCAqQCCQD5nWhzOOjcTjANBgkqhkiG9w0BAQUFADCBnzELMAkGA1UEBhMC
VVMxETAPBgNVBAgMCENvbG9yYWRvMQ8wDQYDVQQHDAZEZW52ZXIxMjAwBgNVBAoM
KUtlbnNpbmd0b24gVGVjaG5vbG9neSBBc3NvY2lhdGVzLCBMaW1pdGVkMRIwEAYD
VQQDDAlsb2NhbGhvc3QxJDAiBgkqhkiG9w0BCQEWFWluZm9Aa25vd2xlZGdla3Rh
LmNvbTAeFw0xNzEwMjcyMDUxMjFaFw0yNzEwMjUyMDUxMjFaMIGfMQswCQYDVQQG
EwJVUzERMA8GA1UECAwIQ29sb3JhZG8xDzANBgNVBAcMBkRlbnZlcjEyMDAGA1UE
CgwpS2Vuc2luZ3RvbiBUZWNobm9sb2d5IEFzc29jaWF0ZXMsIExpbWl0ZWQxEjAQ
BgNVBAMMCWxvY2FsaG9zdDEkMCIGCSqGSIb3DQEJARYVaW5mb0Brbm93bGVkZ2Vr
dGEuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwf/GuDta8rlJ
gImY42RPxXpgSmhbL7XbVb0zA0VnBt2jKuWVHTO33uFU7L0lwtsR3lQNIFIFkgAC
cIbzJCleaub9jilbo1sI8AJY5J2WuoN1341i4KQcvzH7eG9RAwokfcWxBgD6YhoB
jpQ/woWjdV7x7qNaC6fucD+kdzLoCACesUXpipuoQY9VSlpCHzuhDmoArput5XOi
bSkjgvoFZbNaR4rY9BsTo5qUyA8JxZPuPFnLJjeUhmnrVO6R3MDb6IG+YIR6uEh8
0VDsa3hPYTtxuWGv1CqV+Gx2+N36mfYJDw9qd+oHyaxAZklhlHOcEMP5IEJFqFGe
xB1FqN0V+QIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQBUoA3FaB4ezPUmWpRPavuH
OdpmUw1JxpArABFBpCtWXiMwRbf7hsBVGBTIWKZucm7QJ9zeOubsurbNhmAAdYg3
0mKCfikCF5OvGXIbFgJPYbx/GE5/Ch6d8wC29x3jCaG9k4dYZ1xRpPrCQ0eWqjIS
XMZTEHkmeGSObJcxwkvpjCnx8fk6U7SOijsWQ/loUbC2FkM/V1j4pZRXKBeakEXZ
4676VRCrW3tTf4wedwgqC1T8NpZ5ZXtv/SkzLCSdpjshBGO6gnmX670F42bu828D
FFC2NeDZ407Ha33LMSeKiWpCElXPyl/Zfm6QQuWMbkk73krdWr3MnsMoSBc9jn8a
-----END CERTIFICATE-----

**Comment by citizentim** [comment]
Please ignore the rubbish I wrote - I needed the public key, not the full certificate.

**Comment by bin-re** [comment]
I found the bug.
`var Base64=base64();`
Don't use var Base64.

fix to

var self_xxxx_base64 = base64(); ...

**Comment by benmassaoud** [comment]
> I found the bug.
> `var Base64=base64();`
> Don't use var Base64.
> 
> fix to
> 
> var self_xxxx_base64 = base64(); ...

Hi
I've the same problem, where can I change those lines please?

**Comment by DennisAndradeRJ** [comment]
I'm running into this problem. Any luck resolving this?
